# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
# Do similar for other three images

# Tagging
- docker tag udagram-api-feed tuyendhq/udagram-api-feed:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tuyendhq/udagram-api-feed:v1
# Do similar for other three images

# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-user ./udagram-api-user
# Do similar for other three images

# Tagging
- docker tag udagram-api-user tuyendhq/udagram-api-user:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tuyendhq/udagram-api-user:v1
# Do similar for other three images


# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Do similar for other three images

# Tagging
- docker tag udagram-reverseproxy tuyendhq/udagram-reverseproxy:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tuyendhq/udagram-reverseproxy:v1
# Do similar for other three images


# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-frontend ./udagram-frontend
# Do similar for other three images

# Tagging
- docker tag udagram-frontend tuyendhq/udagram-frontend:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tuyendhq/udagram-frontend:v1
# Do similar for other three images